---
title: "Data Science Final Project"
author: "Blair Cha, Kaarin Khandelwal, Dylan Larsen"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Cleaning
```{r}
library(readxl)
library(dplyr)
library(tidyverse)
library(lubridate)
library(countrycode)
library(stringr)
primary_school0 <- read_excel("/Users/hyejeongcha/Documents/Data science final project/primary_school.xlsx")
urban_poverty0 <- read_excel("/Users/hyejeongcha/Documents/Data science final project/urban_poverty.xlsx")
unemployment0 <- read_excel("/Users/hyejeongcha/Documents/Data science final project/unemployment.xlsx")
gdp_capita0 <- read_excel("/Users/hyejeongcha/Documents/Data science final project/gdp_capita.xlsx")
child_mortality0 <- read_excel("/Users/hyejeongcha/Documents/Data science final project/child_mortality.xlsx")
family_workers0 <- read_excel("/Users/hyejeongcha/Documents/Data science final project/family_workers.xlsx")
rural_pop0 <- read_excel("/Users/hyejeongcha/Documents/Data science final project/rural_pop.xlsx")
schooling_cost0 <- read_excel("/Users/hyejeongcha/Documents/Data science final project/schooling_cost.xlsx")
```
```{r}
# Reassembling each dataset to longer style

primary_school <- primary_school0 %>%
  pivot_longer(cols = -country,
               names_to = "year",
               values_to="primary_school") %>%
  mutate(year = as.numeric(year))


urban_poverty <- urban_poverty0 %>%
  pivot_longer(cols = -country,
               names_to = "year",
               values_to="urban_poverty") %>%
    mutate(year = as.numeric(year))

unemployment <- unemployment0 %>%
  pivot_longer(cols = -country,
               names_to = "year",
               values_to="unemployment") %>%
    mutate(year = as.numeric(year))

gdp_capita <- gdp_capita0 %>%
  pivot_longer(cols = -country,
               names_to = "year",
               values_to="gdp_capita") %>%
    mutate(year = as.numeric(year))

child_mortality <- child_mortality0 %>%
  pivot_longer(cols = -country,
               names_to = "year",
               values_to="child_mortality") %>%
    mutate(year = as.numeric(year))

family_workers <- family_workers0 %>%
  pivot_longer(cols = -country,
               names_to = "year",
               values_to="family_workers") %>%
    mutate(year = as.numeric(year))

rural_pop <- rural_pop0 %>%
  pivot_longer(cols = -country,
               names_to = "year",
               values_to="rural_pop") %>%
    mutate(year = as.numeric(year))


schooling_cost <- schooling_cost0 %>%
  pivot_longer(cols = -country,
               names_to = "year",
               values_to="schooling_cost") %>%
    mutate(year = as.numeric(year))
```

```{r}
# Joining every dataset to primary_school

primary_school <- primary_school %>%
  inner_join(urban_poverty, by = c("year","country")) %>%
  inner_join(unemployment, by = c("year","country")) %>%
  inner_join(gdp_capita, by = c("year","country")) %>%
  inner_join(child_mortality, by = c("year","country")) %>%
  inner_join(family_workers, by = c("year","country")) %>%
  inner_join(rural_pop, by = c("year","country")) %>%
  inner_join(schooling_cost, by = c("year","country"))
```

```{r}
# Adding continent variable

newdata <- data.frame(country=primary_school$country)
newdata$continent <- countrycode(sourcevar = primary_school$country, 
                                 origin= "country.name", destination= "continent")
newdata <- newdata %>%
  select(continent, country) %>%
  distinct()

primary_school <- primary_school %>%
  inner_join(newdata, by="country") 

View(primary_school)
```
```{r}
save(primary_school,file="primary_school.Rda") 
#load it with load("Suicide_Rates.Rda")
```


